import 'model/car.dart';
import 'model/carCategory.dart';
import 'package:flutter/material.dart';

List<CarCategory> categories = [
  CarCategory(
      color: const Color.fromARGB(255, 221, 87, 87),
      title: "Audi",
      id: "audi",
      imagePath: "images/logos/PngItem_26377.png"),
  CarCategory(
      color: Colors.black87,
      title: "BMW",
      id: "bmw",
      imagePath: "images/logos/bmw1.png"),
  CarCategory(
      color: Colors.amber,
      title: "Lamborghini",
      id: "lambo",
      imagePath: "images/logos/lamboLogo.png"),
  CarCategory(
      color: Colors.grey.shade500,
      title: "Mercedes Benz",
      id: "merceds",
      imagePath: "images/logos/mercedsLogo.png"),
  CarCategory(
      color: const Color.fromARGB(255, 180, 115, 192),
      title: "Mazda",
      id: "mazda",
      imagePath: "images/logos/mazda.png"),
  CarCategory(
      color: const Color.fromARGB(255, 243, 76, 82),
      title: "Porshe",
      id: "porshe",
      imagePath: "images/logos/porsheLogo.png"),
  CarCategory(
      color: const Color.fromARGB(255, 184, 217, 54),
      title: "travel",
      id: "tr",
      imagePath: ""),
  CarCategory(
      color: const Color.fromARGB(255, 27, 189, 170),
      title: "SuperCars",
      id: "SuperCar",
      imagePath: ""),
  CarCategory(
      color: const Color.fromARGB(255, 76, 137, 243),
      title: "Van",
      id: "van",
      imagePath: ""),
  CarCategory(
      color: const Color.fromARGB(255, 154, 76, 243),
      title: "SUV",
      id: "suv",
      imagePath: ""),
];

List<Car> cars = [
  //Audi Cars

  Car(
      imagePath: "images/audi/audi1.jpg",
      carName: "Audi 1",
      category: ["audi", "SuperCar"],
      maxSpeed: 280,
      acceleration: "40 km/sec",
      fullDescription: [
        "Designed by The germany org audi",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3000,
      hourseAmount: 100),
  Car(
      imagePath: "images/audi/audi2.jpg",
      carName: "Audi 2",
      category: ["audi", "SuperCar"],
      maxSpeed: 280,
      acceleration: "40 km/sec",
      fullDescription: [
        "Designed by The germany org audi",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3000,
      hourseAmount: 100),
  Car(
      imagePath: "images/audi/audi3.jpg",
      carName: "Audi 3",
      category: ["audi", "SuperCar"],
      maxSpeed: 280,
      acceleration: "40 km/sec",
      fullDescription: [
        "Designed by The germany org audi",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3000,
      hourseAmount: 100),
  Car(
      imagePath: "images/audi/audi4.jpg",
      carName: "Audi 4",
      category: ["audi", "SuperCar"],
      maxSpeed: 280,
      acceleration: "40 km/sec",
      fullDescription: [
        "Designed by The germany org audi",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3000,
      hourseAmount: 100),
  Car(
      imagePath: "images/audi/audi5.jpg",
      carName: "Audi 5",
      category: ["audi", "SuperCar", "tr"],
      maxSpeed: 280,
      acceleration: "40 km/sec",
      fullDescription: [
        "Designed by The germany org audi",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3000,
      hourseAmount: 100),

  ///BMW Cars
  Car(
      imagePath: "images/bmw/bestBmw.jpg",
      carName: "BMW 1",
      category: ["bmw", "SuperCar", "tr"],
      maxSpeed: 330,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org bmw",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/bmw/bmw.jpg",
      carName: "BMW 2",
      category: ["bmw", "SuperCar", "tr"],
      maxSpeed: 330,
      acceleration: "70 km/min",
      fullDescription: [
        "Designed by The germany org bmw",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.backWheel,
      minSpeed: 50,
      averagePrice: 3000,
      hourseAmount: 400),
  Car(
      imagePath: "images/bmw/bmw1.jpg",
      carName: "BMW 3",
      category: ["bmw", "SuperCar", "tr"],
      maxSpeed: 330,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org bmw",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/bmw/bmw3.jpg",
      carName: "BMW 4",
      category: ["bmw", "SuperCar", "tr"],
      maxSpeed: 330,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org bmw",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/bmw/bmw4.jpg",
      carName: "BMW 5",
      category: ["bmw", "SuperCar", "tr"],
      maxSpeed: 330,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org bmw",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/bmw/bmw5.jpg",
      carName: "BMW 6",
      category: ["bmw", "SuperCar", "tr"],
      maxSpeed: 330,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org bmw",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/bmw/bmw7.jpg",
      carName: "BMW 8",
      category: ["bmw", "SuperCar", "tr"],
      maxSpeed: 330,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org bmw",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/bmw/bmw8.jpg",
      carName: "BMW 9",
      category: ["bmw", "SuperCar", "tr"],
      maxSpeed: 330,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org bmw",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/bmw/bmw9.jpg",
      carName: "BMW 10",
      category: ["bmw", "SuperCar", "tr"],
      maxSpeed: 330,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org bmw",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),

  ///lamborgini Cars///
  Car(
      imagePath: "images/lambo/lambo1.jpg",
      carName: "Lamborgini 1",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/lambo/lambo2.jpg",
      carName: "Lamborgini 2",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/lambo/lambo3.jpg",
      carName: "Lamborgini 3",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/lambo/lambo4.jpg",
      carName: "Lamborgini 4",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/lambo/lambo5.jpg",
      carName: "Lamborgini 5",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/lambo/lambo6.jpg",
      carName: "Lamborgini 6",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/lambo/lambo7.jpg",
      carName: "Lamborgini 7",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/lambo/lambo8.jpg",
      carName: "Lamborgini 8",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/lambo/lambo9.jpg",
      carName: "Lamborgini 9",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/lambo/lambo10.jpg",
      carName: "Lamborgini 10",
      category: ["lambo", "SuperCar", "van"],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  ////Mazda Cars///
  Car(
      imagePath: "images/mazda/mazda1.jpg",
      carName: "Mazda 1",
      category: [
        "mazda",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/mazda/mazda2.jpg",
      carName: "Mazda 2",
      category: [
        "mazda",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),

  Car(
      imagePath: "images/mazda/mazda3.jpg",
      carName: "Mazda 3",
      category: [
        "mazda",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3600,
      hourseAmount: 400),

  Car(
      imagePath: "images/mazda/mazda4.jpg",
      carName: "Mazda 4",
      category: [
        "mazda",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3370,
      hourseAmount: 400),
  //Merceds Cars

  Car(
      imagePath: "images/merceds/merceds1.jpg",
      carName: "merceds 1",
      category: [
        "merceds",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3360,
      hourseAmount: 400),

  Car(
      imagePath: "images/merceds/merceds2.jpg",
      carName: "merceds 2",
      category: [
        "merceds",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/merceds/merceds3.jpg",
      carName: "merceds 3",
      category: [
        "merceds",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3360,
      hourseAmount: 400),
  Car(
      imagePath: "images/merceds/merceds4.jpg",
      carName: "merceds 4",
      category: [
        "merceds",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3000,
      hourseAmount: 400),
  Car(
      imagePath: "images/merceds/merceds5.jpg",
      carName: "merceds 5",
      category: [
        "merceds",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/merceds/merceds6.jpg",
      carName: "merceds 6",
      category: [
        "merceds",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/merceds/merceds7.jpg",
      carName: "merceds 7",
      category: [
        "merceds",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/merceds/merceds8.jpg",
      carName: "merceds 8",
      category: [
        "merceds",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
  Car(
      imagePath: "images/merceds/merceds9.jpg",
      carName: "merceds 9",
      category: [
        "merceds",
        "SuperCar",
      ],
      maxSpeed: 380,
      acceleration: "80 km/min",
      fullDescription: [
        "Designed by The germany org Lamborghini",
        "has a lot of colors black , white",
        "it is so famous across all the world ",
        "it is so fast yeah ",
        "hurry up man and get one of this cars"
            "Using for speed Races and for general uses all time",
      ],
      price: priceRange.luxuriy,
      type: typeWheel.frontWheel,
      minSpeed: 50,
      averagePrice: 3300,
      hourseAmount: 400),
];
